# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
    build:
        docker:
        - image: circleci/golang:1.15
        working_directory: /go/src/github.com/slysterous/custom-number
        steps:
        - checkout
        - run: go get golang.org/x/lint/golint
        - run: make fmt
        - run: make ci