# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
    codecov: codecov/codecov@1.1.1

jobs:
    build:
        docker:
        - image: circleci/golang:1.15
        working_directory: /go/src/github.com/slysterous/custom-number
        steps:
        - checkout
        - run: go get golang.org/x/lint/golint
        - run: make fmt
        - run: make ci
        - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        - codecov/upload:
            file: './coverage.txt'
            token: 9b1131be-d1fa-4091-bf1d-2761a84e3f3b

